name: CI
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install stable rust
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: stable
            override: true

      - name: 'Lint Markdown'
        run: |
          find . -name "*.md" -exec markdown-link-check {} \;
      - name: Pull Private Submodule BTIGhidra
        env:
          SSHK: ${{ secrets.BTI_GHIDRA_DEPLOY }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSHK" > $HOME/.ssh/ssh.key
          chmod 600 $HOME/.ssh/ssh.key
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
          git submodule update --init -- ./BTIGhidra
      - name: Pull Private Submodule binary_type_inference
        env:
          SSHK: ${{ secrets.BTI_RUST_DEPLOY }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSHK" > $HOME/.ssh/ssh.key
          chmod 600 $HOME/.ssh/ssh.key
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
          git submodule update --init -- ./BTIGhidra/binary_type_inference

      - name: Pull Private Submodule CWE_Checker
        env:
          SSHK: ${{ secrets.CWE_DEPLOY }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSHK" > $HOME/.ssh/ssh.key
          chmod 600 $HOME/.ssh/ssh.key
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
          git submodule update --init -- ./BTIGhidra/binary_type_inference/cwe_checker

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: 'Setup Ghidra'
        run: |
          wget https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.1.5_build/ghidra_10.1.5_PUBLIC_20220726.zip --output-document=ghidra.zip
          unzip ghidra.zip
          echo "GHIDRA_INSTALL_DIR=$(pwd)/ghidra_10.1.5_PUBLIC" >> $GITHUB_ENV
